export const countryData = [
    // Default — Guinea first
    { code: "+224", iso: "GN", flag: "🇬🇳", name: "Guinea", placeholder: "6XX XX XX XX", digits: 9 },

    // West Africa
    { code: "+221", iso: "SN", flag: "🇸🇳", name: "Senegal", placeholder: "7X XXX XX XX", digits: 9 },
    { code: "+225", iso: "CI", flag: "🇨🇮", name: "Ivory Coast", placeholder: "0X XX XX XX XX", digits: 10 },
    { code: "+223", iso: "ML", flag: "🇲🇱", name: "Mali", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+220", iso: "GM", flag: "🇬🇲", name: "Gambia", placeholder: "XXX XXXX", digits: 7 },
    { code: "+245", iso: "GW", flag: "🇬🇼", name: "Guinea-Bissau", placeholder: "XXX XXXX", digits: 7 },
    { code: "+232", iso: "SL", flag: "🇸🇱", name: "Sierra Leone", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+231", iso: "LR", flag: "🇱🇷", name: "Liberia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+234", iso: "NG", flag: "🇳🇬", name: "Nigeria", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+233", iso: "GH", flag: "🇬🇭", name: "Ghana", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+228", iso: "TG", flag: "🇹🇬", name: "Togo", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+229", iso: "BJ", flag: "🇧🇯", name: "Benin", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+226", iso: "BF", flag: "🇧🇫", name: "Burkina Faso", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+227", iso: "NE", flag: "🇳🇪", name: "Niger", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+222", iso: "MR", flag: "🇲🇷", name: "Mauritania", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+238", iso: "CV", flag: "🇨🇻", name: "Cape Verde", placeholder: "XXX XX XX", digits: 7 },

    // Central Africa
    { code: "+237", iso: "CM", flag: "🇨🇲", name: "Cameroon", placeholder: "X XX XX XX XX", digits: 9 },
    { code: "+241", iso: "GA", flag: "🇬🇦", name: "Gabon", placeholder: "X XX XX XX", digits: 7 },
    { code: "+242", iso: "CG", flag: "🇨🇬", name: "Congo", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+243", iso: "CD", flag: "🇨🇩", name: "DR Congo", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+235", iso: "TD", flag: "🇹🇩", name: "Chad", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+236", iso: "CF", flag: "🇨🇫", name: "Central African Republic", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+240", iso: "GQ", flag: "🇬🇶", name: "Equatorial Guinea", placeholder: "XXX XXX XXX", digits: 9 },

    // East Africa
    { code: "+254", iso: "KE", flag: "🇰🇪", name: "Kenya", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+255", iso: "TZ", flag: "🇹🇿", name: "Tanzania", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+256", iso: "UG", flag: "🇺🇬", name: "Uganda", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+250", iso: "RW", flag: "🇷🇼", name: "Rwanda", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+251", iso: "ET", flag: "🇪🇹", name: "Ethiopia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+252", iso: "SO", flag: "🇸🇴", name: "Somalia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+253", iso: "DJ", flag: "🇩🇯", name: "Djibouti", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+257", iso: "BI", flag: "🇧🇮", name: "Burundi", placeholder: "XX XX XXXX", digits: 8 },
    { code: "+291", iso: "ER", flag: "🇪🇷", name: "Eritrea", placeholder: "X XXX XXX", digits: 7 },

    // Southern Africa
    { code: "+27", iso: "ZA", flag: "🇿🇦", name: "South Africa", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+263", iso: "ZW", flag: "🇿🇼", name: "Zimbabwe", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+260", iso: "ZM", flag: "🇿🇲", name: "Zambia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+258", iso: "MZ", flag: "🇲🇿", name: "Mozambique", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+261", iso: "MG", flag: "🇲🇬", name: "Madagascar", placeholder: "XX XX XXX XX", digits: 9 },
    { code: "+265", iso: "MW", flag: "🇲🇼", name: "Malawi", placeholder: "X XXXX XXXX", digits: 9 },
    { code: "+267", iso: "BW", flag: "🇧🇼", name: "Botswana", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+264", iso: "NA", flag: "🇳🇦", name: "Namibia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+266", iso: "LS", flag: "🇱🇸", name: "Lesotho", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+268", iso: "SZ", flag: "🇸🇿", name: "Eswatini", placeholder: "XX XX XXXX", digits: 8 },

    // North Africa
    { code: "+212", iso: "MA", flag: "🇲🇦", name: "Morocco", placeholder: "XXX XX XX XX", digits: 9 },
    { code: "+213", iso: "DZ", flag: "🇩🇿", name: "Algeria", placeholder: "XXX XX XX XX", digits: 9 },
    { code: "+216", iso: "TN", flag: "🇹🇳", name: "Tunisia", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+218", iso: "LY", flag: "🇱🇾", name: "Libya", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+20", iso: "EG", flag: "🇪🇬", name: "Egypt", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+249", iso: "SD", flag: "🇸🇩", name: "Sudan", placeholder: "XX XXX XXXX", digits: 9 },

    // Europe
    { code: "+33", iso: "FR", flag: "🇫🇷", name: "France", placeholder: "X XX XX XX XX", digits: 9 },
    { code: "+44", iso: "GB", flag: "🇬🇧", name: "United Kingdom", placeholder: "XXXX XXXXXX", digits: 10 },
    { code: "+49", iso: "DE", flag: "🇩🇪", name: "Germany", placeholder: "XXX XXXXXXX", digits: 10 },
    { code: "+34", iso: "ES", flag: "🇪🇸", name: "Spain", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+39", iso: "IT", flag: "🇮🇹", name: "Italy", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+351", iso: "PT", flag: "🇵🇹", name: "Portugal", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+31", iso: "NL", flag: "🇳🇱", name: "Netherlands", placeholder: "X XXXXXXXX", digits: 9 },
    { code: "+32", iso: "BE", flag: "🇧🇪", name: "Belgium", placeholder: "XXX XX XX XX", digits: 9 },
    { code: "+41", iso: "CH", flag: "🇨🇭", name: "Switzerland", placeholder: "XX XXX XX XX", digits: 9 },
    { code: "+43", iso: "AT", flag: "🇦🇹", name: "Austria", placeholder: "XXX XXXXXXX", digits: 10 },
    { code: "+46", iso: "SE", flag: "🇸🇪", name: "Sweden", placeholder: "XX XXX XX XX", digits: 9 },
    { code: "+47", iso: "NO", flag: "🇳🇴", name: "Norway", placeholder: "XXX XX XXX", digits: 8 },
    { code: "+45", iso: "DK", flag: "🇩🇰", name: "Denmark", placeholder: "XX XX XX XX", digits: 8 },
    { code: "+358", iso: "FI", flag: "🇫🇮", name: "Finland", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+48", iso: "PL", flag: "🇵🇱", name: "Poland", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+420", iso: "CZ", flag: "🇨🇿", name: "Czech Republic", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+36", iso: "HU", flag: "🇭🇺", name: "Hungary", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+40", iso: "RO", flag: "🇷🇴", name: "Romania", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+30", iso: "GR", flag: "🇬🇷", name: "Greece", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+353", iso: "IE", flag: "🇮🇪", name: "Ireland", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+7", iso: "RU", flag: "🇷🇺", name: "Russia", placeholder: "XXX XXX XX XX", digits: 10 },
    { code: "+380", iso: "UA", flag: "🇺🇦", name: "Ukraine", placeholder: "XX XXX XX XX", digits: 9 },
    { code: "+90", iso: "TR", flag: "🇹🇷", name: "Turkey", placeholder: "XXX XXX XXXX", digits: 10 },

    // Americas
    { code: "+1", iso: "US", flag: "🇺🇸", name: "United States", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+1", iso: "CA", flag: "🇨🇦", name: "Canada", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+52", iso: "MX", flag: "🇲🇽", name: "Mexico", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+55", iso: "BR", flag: "🇧🇷", name: "Brazil", placeholder: "XX XXXXX XXXX", digits: 11 },
    { code: "+54", iso: "AR", flag: "🇦🇷", name: "Argentina", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+57", iso: "CO", flag: "🇨🇴", name: "Colombia", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+56", iso: "CL", flag: "🇨🇱", name: "Chile", placeholder: "X XXXX XXXX", digits: 9 },
    { code: "+51", iso: "PE", flag: "🇵🇪", name: "Peru", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+58", iso: "VE", flag: "🇻🇪", name: "Venezuela", placeholder: "XXX XXX XXXX", digits: 10 },

    // Middle East
    { code: "+971", iso: "AE", flag: "🇦🇪", name: "UAE", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+966", iso: "SA", flag: "🇸🇦", name: "Saudi Arabia", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+974", iso: "QA", flag: "🇶🇦", name: "Qatar", placeholder: "XXXX XXXX", digits: 8 },
    { code: "+965", iso: "KW", flag: "🇰🇼", name: "Kuwait", placeholder: "XXXX XXXX", digits: 8 },
    { code: "+968", iso: "OM", flag: "🇴🇲", name: "Oman", placeholder: "XXXX XXXX", digits: 8 },
    { code: "+973", iso: "BH", flag: "🇧🇭", name: "Bahrain", placeholder: "XXXX XXXX", digits: 8 },
    { code: "+962", iso: "JO", flag: "🇯🇴", name: "Jordan", placeholder: "X XXXX XXXX", digits: 9 },
    { code: "+961", iso: "LB", flag: "🇱🇧", name: "Lebanon", placeholder: "XX XXX XXX", digits: 8 },
    { code: "+964", iso: "IQ", flag: "🇮🇶", name: "Iraq", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+98", iso: "IR", flag: "🇮🇷", name: "Iran", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+972", iso: "IL", flag: "🇮🇱", name: "Israel", placeholder: "XX XXX XXXX", digits: 9 },

    // Asia
    { code: "+91", iso: "IN", flag: "🇮🇳", name: "India", placeholder: "XXXXX XXXXX", digits: 10 },
    { code: "+92", iso: "PK", flag: "🇵🇰", name: "Pakistan", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+880", iso: "BD", flag: "🇧🇩", name: "Bangladesh", placeholder: "XXXX XXX XXX", digits: 10 },
    { code: "+86", iso: "CN", flag: "🇨🇳", name: "China", placeholder: "XXX XXXX XXXX", digits: 11 },
    { code: "+81", iso: "JP", flag: "🇯🇵", name: "Japan", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+82", iso: "KR", flag: "🇰🇷", name: "South Korea", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+66", iso: "TH", flag: "🇹🇭", name: "Thailand", placeholder: "X XXXX XXXX", digits: 9 },
    { code: "+84", iso: "VN", flag: "🇻🇳", name: "Vietnam", placeholder: "XX XXX XX XX", digits: 9 },
    { code: "+62", iso: "ID", flag: "🇮🇩", name: "Indonesia", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+60", iso: "MY", flag: "🇲🇾", name: "Malaysia", placeholder: "XX XXXX XXXX", digits: 10 },
    { code: "+63", iso: "PH", flag: "🇵🇭", name: "Philippines", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+65", iso: "SG", flag: "🇸🇬", name: "Singapore", placeholder: "XXXX XXXX", digits: 8 },
    { code: "+94", iso: "LK", flag: "🇱🇰", name: "Sri Lanka", placeholder: "XX XXX XXXX", digits: 9 },
    { code: "+95", iso: "MM", flag: "🇲🇲", name: "Myanmar", placeholder: "X XXX XXXX", digits: 8 },
    { code: "+977", iso: "NP", flag: "🇳🇵", name: "Nepal", placeholder: "XXX XXX XXXX", digits: 10 },
    { code: "+93", iso: "AF", flag: "🇦🇫", name: "Afghanistan", placeholder: "XX XXX XXXX", digits: 9 },

    // Oceania
    { code: "+61", iso: "AU", flag: "🇦🇺", name: "Australia", placeholder: "XXX XXX XXX", digits: 9 },
    { code: "+64", iso: "NZ", flag: "🇳🇿", name: "New Zealand", placeholder: "XX XXX XXXX", digits: 9 },
];
